const PowerUpType = {
    SHIELD: 'SHIELD',
    CADENCY: 'CADENCY',
    DOUBLE_POINTS: 'DOUBLE_POINTS',
    FREEZE: 'FREEZE',
    SPEED: 'SPEED',
    NOENEMYBULLETS: 'NOENEMYBULLETS',
    EXTRA_LIFE: 'EXTRA_LIFE'
  };